name: tmos

channels:
  - conda-forge

dependencies:
  - python=3.11
  - pip
  - rdkit>=2025.3.3
  - openbabel
  - mdanalysis>=2.10.0
  - networkx
  - qcelemental
  - periodictable
  - numpy
  - deepdiff
  - py3Dmol
  - loguru
  - pymatgen

  - pydata-sphinx-theme
  - sphinx-design
  - sphinx-copybutton
  - nbsphinx
